# Generated by Django 5.2.3 on 2025-06-24 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0003_alter_comment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtime',
            name='status',
        ),
        migrations.DeleteModel(
            name='OvertimeStatus',
        ),
    ]
