# Generated by Django 5.2.3 on 2025-06-26 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0004_remove_overtime_status_delete_overtimestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimefile',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='overtime.fileupload'),
        ),
    ]
